apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "Test"
  annotations:
    'backstage.io/kubernetes-namespace': backstage
    'backstage.io/kubernetes-label-selector': 'app=backstage'
    'github.com/project-slug': 'tpoingt/tutorial'
    backstage.io/linguist: 'https://github.com/tpoingt/tutorial'
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
